#if !canImport(ObjectiveC)
  import XCTest

  extension GreetingsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GreetingsTests = [
      ("testExample", testExample),
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(GreetingsTests.__allTests__GreetingsTests),
    ]
  }
#endif
